SVM = Support Vector Machine
Steps:
    1) Data collection
        import pandas as pd
    2) Data Preprocessing
        i) If Nominal--> One hot encoding (pd.get_dummies(variable,drop_first=True))
        ii) If Ordinal--> Mapping--> Label encoding
    3) Input & output split
        i/p variable=variable[["-","-",...]]
        o/p variable=variable[["-","-",...]]
    4) Train & test split
        from sklearn.model_selection import train_test_split
    5) Considering train set
        i) If needed apply standardization to (x_train & x_test)
        from sklearn.preprocessing import StandardScaler
    6) Model Creation
        from sklearn.Linear_model/svm import LinearRegression/SVR
    7) Selection of best model by applying different algorithms to the model
        i) Simple Linear Regression algorithm
        ii) Multiple Linear Regression algorithm
        iii) SVM
        iv) DT
        v) RF, etc
    8) Find predicted value(y_predict) by applying into x_test
    9) Apply y_predict to y_test
    10) Find r2_score value (analyze whwther the value is nearing (0 or 1)
    from sklearn.metrics import r2_score
    11) Finalize the best model
    12) Save the model in a file as binary format
    13) Give input & see the result & deploy it

In [2]:
import pandas as pd

In [6]:
dataset=pd.read_csv("50_Startups.csv")
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [7]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156991.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.95,311613.29,152211.77,0,1
9,123334.88,108679.17,304981.62,149759.96,0,0
10,101913.08,110594.11,229160.95,146121.95,1,0
11,100671.96,91790.61,249744.55,144259.40,0,0
12,93863.75,127320.38,249839.44,141585.52,1,0
13,91992.39,135495.07,252664.93,134307.35,0,0
14,119943.24,156547.42,256512.92,132602.65,1,0
15,114523.61,122616.84,261776.23,129917.04,0,1
16,78013.11,121597.55,264346.06,126992.93,0,0
17,94657.16,145077.58,282574.31,125370.37,0,1
18,91749.16,114175.79,294919.57,124266.90,1,0
19,86419.70,153514.11,0.00,122776.86,0,1
20,76253.86,113867.30,298664.47,118474.03,0,0
21,78389.47,153773.43,299737.29,111313.02,0,1
22,73994.56,122782.75,303319.26,110352.25,1,0
23,67532.53,105751.03,304768.73,108733.99,1,0
24,77044.01,99281.34,140574.81,108552.04,0,1
25,64664.71,139553.16,137962.62,107404.34,0,0
26,75328.87,144135.98,134050.07,105733.54,1,0
27,72107.60,127864.55,353183.81,105008.31,0,1
28,66051.52,182645.56,118148.20,103282.38,1,0
29,65605.48,153032.06,107138.38,101004.64,0,1
30,61994.48,115641.28,91131.24,99937.59,1,0
31,61136.38,152701.92,88218.23,97483.56,0,1
32,63408.86,129219.61,46085.25,97427.84,0,0
33,55493.95,103057.49,214634.81,96778.92,1,0
34,46426.07,157693.92,210797.67,96712.80,0,0
35,46014.02,85047.44,205517.64,96479.51,0,1
36,28663.76,127056.21,201126.82,90708.19,1,0
37,44069.95,51283.14,197029.42,89949.14,0,0
38,20229.59,65947.93,185265.10,81229.06,0,1
39,38558.51,82982.09,174999.30,81005.76,0,0
40,28754.33,118546.05,172795.67,78239.91,0,0
41,27892.92,84710.77,164470.71,77798.83,1,0
42,23640.93,96189.63,148001.11,71498.49,0,0
43,15505.73,127382.30,35534.17,69758.98,0,1
44,22177.74,154806.14,28334.72,65200.33,0,0
45,1000.23,124153.04,1903.93,64926.08,0,1
46,1315.46,115816.21,297114.46,49490.75,1,0
47,0.00,135426.92,0.00,42559.73,0,0
48,542.05,51743.15,0.00,35673.41,0,1
49,0.00,116983.80,45173.06,14681.40,0,0

In [8]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [9]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]

In [11]:
dependent=dataset[['Profit']]

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(independent, dependent, test_size=0.20, random_state=0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [20]:
x_train

array([[-0.35006454, -0.78547109,  0.1011968 ,  1.73205081, -0.73379939],
       [-0.55530319, -1.48117426,  0.02734979, -0.57735027,  1.36277029],
       [ 0.07935762,  0.80133381, -0.55152132,  1.73205081, -0.73379939],
       [-0.54638238,  1.32505817,  0.07011684, -0.57735027, -0.73379939],
       [ 0.43485371, -0.35598663,  0.75148516,  1.73205081, -0.73379939],
       [ 1.26943143,  0.85518519,  0.98603118,  1.73205081, -0.73379939],
       [ 1.04525007,  1.28077047,  0.4404    ,  1.73205081, -0.73379939],
       [-1.529843  ,  0.02942065, -1.6218751 , -0.57735027,  1.36277029],
       [-1.53976251, -2.76767264, -1.6372965 , -0.57735027,  1.36277029],
       [-0.13115188,  1.14497701, -0.76949991, -0.57735027,  1.36277029],
       [ 0.92791613, -0.02992062,  0.48303162, -0.57735027,  1.36277029],
       [-0.20932933, -0.2993768 , -0.89915412,  1.73205081, -0.73379939],
       [-0.17870828,  0.2251352 , -1.26401642, -0.57735027, -0.73379939],
       [ 0.1374709 , -0.06929437,  0.50384666, -0.57735027, -0.73379939],
       [-1.03967624, -1.05076697, -0.43852106, -0.57735027, -0.73379939],
       [ 0.09938348, -0.36790317,  0.781818  , -0.57735027, -0.73379939],
       [-1.21580174,  0.15416247, -1.34947778, -0.57735027,  1.36277029],
       [ 1.05822437,  0.97836757,  0.88670051, -0.57735027,  1.36277029],
       [ 0.4401196 ,  0.46754749,  0.40923215, -0.57735027, -0.73379939],
       [-0.15151937,  0.62430586, -0.51983056, -0.57735027, -0.73379939],
       [ 1.30361149, -0.91073517,  1.30179825, -0.57735027,  1.36277029],
       [ 0.49781135,  0.83770651,  0.65149135, -0.57735027,  1.36277029],
       [-0.92897212, -0.18716957, -0.23769075, -0.57735027, -0.73379939],
       [-1.55149779, -0.24751712, -1.27140496, -0.57735027, -0.73379939],
       [ 1.96871085,  1.08106713,  1.95818096, -0.57735027, -0.73379939],
       [ 0.48063418,  0.15177059,  0.38634632,  1.73205081, -0.73379939],
       [-0.59739193, -2.78544219, -0.04140287, -0.57735027, -0.73379939],
       [ 0.11649007, -0.93133851, -0.49867241, -0.57735027,  1.36277029],
       [ 1.36290079,  0.91964899, -0.60281921, -0.57735027, -0.73379939],
       [-0.08943162, -0.68142339,  0.83126112,  1.73205081, -0.73379939],
       [-0.93093295,  0.14156607, -0.00821485,  1.73205081, -0.73379939],
       [ 0.14561902,  1.1736151 ,  0.7905076 , -0.57735027,  1.36277029],
       [ 0.31947194,  1.16359793, -1.6372965 , -0.57735027,  1.36277029],
       [ 1.11867842, -0.56831342,  0.83298548, -0.57735027, -0.73379939],
       [-0.71671353, -1.56095586, -0.21984184, -0.57735027, -0.73379939],
       [-1.52301833, -0.29261949,  0.76926327,  1.73205081, -0.73379939],
       [ 1.57413686, -0.18231009,  1.46653355, -0.57735027,  1.36277029],
       [ 2.02828029,  0.52173299,  2.18404776, -0.57735027,  1.36277029],
       [-1.55149779,  0.46491495, -1.6372965 , -0.57735027, -0.73379939],
       [-1.07135402,  1.21350725, -1.40779169, -0.57735027, -0.73379939]])

In [21]:
x_test

array([[-0.1214952 ,  2.2889053 , -0.68032287,  1.73205081, -0.73379939],
       [ 0.6280306 , -1.22069499,  0.38557774, -0.57735027, -0.73379939],
       [ 0.65490061, -0.49434195,  0.21885524,  1.73205081, -0.73379939],
       [-0.94762148, -1.49417936, -0.30512104,  1.73205081, -0.73379939],
       [ 1.77048111, -0.85932667,  1.6668808 ,  1.73205081, -0.73379939],
       [ 0.00961775,  0.17279112,  1.22341229, -0.57735027,  1.36277029],
       [-1.11353109, -2.21896176, -0.13669119, -0.57735027,  1.36277029],
       [-0.22790703,  1.13222416, -0.92274884, -0.57735027,  1.36277029],
       [ 0.05047007, -0.02351175,  0.81952074,  1.73205081, -0.73379939],
       [ 1.52509853, -1.23610162,  1.32858469,  1.73205081, -0.73379939]])

In [83]:
from sklearn.svm import SVR
regressor=SVR(kernel="linear",C=1000)
regressor.fit(x_train, y_train)

C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000, kernel='linear')

In [84]:
y_predict=regressor.predict(x_test)
y_predict

array([106326.92103228, 123104.34034876, 123244.0822852 ,  83023.55784889,
       158799.82821258, 123862.18150654,  81601.61897116, 101007.56059925,
       118015.12147478, 149562.788621  ])

In [85]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test, y_predict)
r_score

0.7849121652938659