In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]

In [6]:
dependent=dataset[['charges']]

In [7]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.20,random_state=0)

In [8]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# x_train=sc.fit_transform(x_train)
# x_test=sc.transform(x_test)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor 
grid_params={'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
             'n_estimators':[10,50,100,500],
             'max_features':['None','sqrt','log2','auto']
            }
grid=GridSearchCV(RandomForestRegressor(),grid_params,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 64 candidates, totalling 320 fits

C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
80 fits failed out of a total of 320.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 340, in fit
    self._validate_params()
  File "C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py", line 581, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt', 'auto' (deprecated)} or None. Got 'None' instead.

--------------------------------------------------------------------------------
67 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 340, in fit
    self._validate_params()
  File "C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py", line 581, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'auto' (deprecated), 'sqrt', 'log2'} or None. Got 'None' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan 0.81825883 0.82901825
 0.83348539 0.83447853 0.81495678 0.82980505 0.83469135 0.83475594
 0.81358053 0.82373684 0.82671151 0.82781551        nan        nan
        nan        nan 0.818744   0.83200263 0.83250107 0.83511731
 0.81599123 0.82925427 0.83398888 0.83460548 0.81250189 0.8237007
 0.82487944 0.82783686        nan        nan        nan        nan
 0.81819401 0.8302727  0.83216064 0.83342087 0.82041349 0.82917264
 0.83353507 0.83450238 0.80928909 0.82176578 0.82310261 0.82371855
        nan        nan        nan        nan 0.81848515 0.82906842
 0.83216658 0.83531543 0.81767199 0.83093608 0.83564379 0.83536818
 0.81624636 0.82602769 0.82822393 0.82776772]
  warnings.warn(
C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:909: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['None', 'sqrt', 'log2', 'auto'],
                         'n_estimators': [10, 50, 100, 500]},
             verbose=3)

In [10]:
result=grid.cv_results_
# result
print("result is {}".format(grid.best_params_))

result is {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 100}

In [11]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004198,0.002315,0.000000,0.000000,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,49
1,0.005598,0.006708,0.000000,0.000000,squared_error,None,50,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,49
2,0.003597,0.001019,0.000000,0.000000,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,49
3,0.007995,0.006063,0.000000,0.000000,squared_error,None,500,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,49
4,0.175890,0.056136,0.018390,0.009129,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.827585,0.747193,0.857151,0.821638,0.837728,0.818259,0.037524,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,5.319526,0.631814,0.254245,0.107217,poisson,log2,500,"{'criterion': 'poisson', 'max_features': 'log2...",0.859494,0.780912,0.862709,0.831401,0.842326,0.835368,0.029527,2
60,0.278026,0.006521,0.020188,0.000399,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",0.840789,0.741105,0.839153,0.817293,0.842892,0.816246,0.038690,43
61,0.594631,0.155858,0.017791,0.002134,poisson,auto,50,"{'criterion': 'poisson', 'max_features': 'auto...",0.847958,0.770571,0.852804,0.821517,0.837287,0.826028,0.029734,30
62,1.831672,0.537088,0.056966,0.032346,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",0.851655,0.772163,0.855704,0.823742,0.837857,0.828224,0.030199,25
63,7.664485,0.557657,0.192881,0.091480,poisson,auto,500,"{'criterion': 'poisson', 'max_features': 'auto...",0.848585,0.772446,0.858377,0.820160,0.839271,0.827768,0.030401,28

In [12]:
'age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'
age=int(input("Enter the Age: "))
bmi=int(input("Enter the BMI_range: "))
children=int(input("Enter the Children_count: "))
sex_male=int(input("Enter the sex, male 1/female 0: "))
smoker_yes=int(input("Enter the smoker, yes 1/no 0): "))

pred=grid.predict([[age,bmi,children,sex_male,smoker_yes]])
print("Prediction is: {}".format(pred))

Enter the Age: 59
Enter the BMI_range: 32
Enter the Children_count: 2
Enter the sex, male 1/female 0: 1
Enter the smoker, yes 1/no 0): 1
Prediction is: [45019.7309226]

C:\Users\jayac\AppData\Local\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(