In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [36]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [37]:
dependent=[['charges']]

In [38]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.20,random_state=0)

In [39]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# x_train=sc.fit_transform(x_train)
# x_test=sc.transform(x_test)

In [40]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostRegressor
grid_params={"n_estimators": [10,50,100],
             "learning_rate": [10,50],
             "loss": ["linear","square","exponential"]
            }
grid=GridSearchCV(AdaBoostRegressor(),grid_params,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

ValueError: Found input variables with inconsistent numbers of samples: [1338, 1]

In [ ]:
results=grid.cv_results_
print("The result is : {}".format(grid.best.params))

In [ ]:
table=pd.DataFrame.from_dict(results)
table

In [ ]:
'age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'
age=int(input("Enter the Age: "))
bmi=int(input("Enter the BMI_range: "))
children=int(input("Enter the Children_count: "))
sex_male=int(input("Enter the sex, male 1/female 0: "))
smoker_yes=int(input("Enter the smoker, yes 1/no 0): "))

pred=grid.predict([[age,bmi,children,sex_male,smoker_yes]])
print("Prediction is: {}".format(pred))